CREATE TABLE Problems (
	Id INT NOT NULL,
	ProblemAreaId INT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE ProblemAreas (
	Id INT NOT NULL,
	Name VARCHAR(64) NOT NULL,
	Description TEXT(1),
	Created DATETIME NOT NULL,
	CreatedBy INT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE Users (
	Id INT NOT NULL,
	Username VARCHAR(32) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Email VARCHAR(64) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE Table1 (
);

ALTER TABLE ProblemAreas ADD CONSTRAINT ProblemAreas_Users_FK FOREIGN KEY (CreatedBy)
	REFERENCES Users (Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

ALTER TABLE Problems ADD CONSTRAINT Problem_ProblemAreas_FK FOREIGN KEY (ProblemAreaId)
	REFERENCES ProblemAreas (Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

