<?php

/**
 * Dynamic translation 
 * 
 * This translations are mostly generated, so to enable their recognition, we need to save them 
 * as a dummy data to the project ;-)
 **/
__('role_guest');
__('role_moderator');
__('role_user');
__('role_administrator');
__('PROBLEM_DEFINE');
__('PROBLEM_ADD_COMMENT');
__('PROBLEM_ACCEPT_VOTE');
__('PROBLEM_ACCEPT');
__('PROBLEM_ADD_SOLUTION');
__('USERS_SEARCH');
__('PROBLEM_VIEW_ACCEPT_STATS');
__('PERMISSIONS_EDIT');
__('resource_group_OUTPUT');
__('OUTPUT_OPTIMALORDER');
__('PROBLEM_SOLVE');
__('PROBLEM_IMPORTANCE_VOTE');
__('resource_group_SOLUTION');
__('SOLUTION_VIEW_STATS');
__('SOLUTION_MANAGE_DEPENDENCY');
__('SOLUTION_CREATE');
__('SOLUTION_ACCEPT_VOTE');
__('SOLUTION_ACCEPT');


/** Resources */
__('resource_group_PERMISSIONS');
__('resource_group_PROBLEM');
__('resource_group_USERS');


/** Validation errors */
__('isEmpty');
__('emailAddressInvalid');
__('emailAddressInvalidHostname');
__('emailAddressInvalidMxRecord');
__('emailAddressDotAtom');
__('emailAddressQuotedString');
__('emailAddressInvalidLocalPart');


/** Problem states */
__('problemstate_NEW');
__('problemstate_APPROVED');
__('problemstate_SOLVED');
__('problemstate_CLOSED');
__('problemstate_DELETED');

/** Vote states */
__('VOTE_Yes');
__('VOTE_No');
__('VOTE_Ignore');

/** History events */
__('EVENT_CREATE');
__('EVENT_APPROVE');
__('EVENT_DECLINE');
__('EVENT_CHANGE');
__('EVENT_SOLVE');

__('SOLUTIONEVENT_CREATE');
__('SOLUTIONEVENT_APPROVE');
__('SOLUTIONEVENT_DECLINE');


/** /user/view */
__('USR_ACCSTATUS_0');
__('USR_ACCSTATUS_1');
?>