<?php

/**
 * Dynamic translation 
 * 
 * This translations are mostly generated, so to enable their recognition, we need to save them 
 * as a dummy data to the project ;-)
 **/
__('role_guest');
__('role_moderator');
__('role_user');
__('role_administrator');
__('PROBLEM_DEFINE');
__('PROBLEM_ADD_COMMENT');
__('PROBLEM_ACCEPT_VOTE');
__('PROBLEM_ACCEPT');
__('PROBLEM_ADD_SOLUTION');
__('USERS_SEARCH');
?>