<?php $this->placeholder('nav')->captureStart('APPEND'); ?>
	<div class="menuBox">
		<span class="title"><?=$this->translate('Index BOX'); ?></span>
		<a class="row" href="/problemarea/index"><?=$this->translate('View problem areas');?></a>	
	</div>
<?php $this->placeholder('nav')->captureEnd('APPEND'); ?>

<h2><?=$this->translate('WELCOME') ?></h2>

<p>
	Vitajte v kolaboračnom informačnom systéme. Tento systém slúži na ....
</p>

<a href="/problemarea/index">Zobraziť zoznam problémových oblastí</a>