<?php

/**
 * Dynamic translation 
 * 
 * This translations are mostly generated, so to enable their recognition, we need to save them 
 * as a dummy data to the project ;-)
 **/
__('role_guest');
__('role_moderator');
__('role_user');
__('role_administrator');
__('PROBLEM_DEFINE');
__('PROBLEM_ADD_COMMENT');
__('PROBLEM_ACCEPT_VOTE');
__('PROBLEM_ACCEPT');
__('PROBLEM_ADD_SOLUTION');
__('USERS_SEARCH');
__('PROBLEM_VIEW_ACCEPT_STATS');
__('PERMISSIONS_EDIT');

/** Resources */
__('resource_group_PERMISSIONS');
__('resource_group_PROBLEM');
__('resource_group_USERS');


/** Validation errors */
__('isEmpty');
__('emailAddressInvalid');
__('emailAddressInvalidHostname');
__('emailAddressInvalidMxRecord');
__('emailAddressDotAtom');
__('emailAddressQuotedString');
__('emailAddressInvalidLocalPart');


/** Problem states */
__('problemstate_NEW');
__('problemstate_APPROVED');
__('problemstate_SOLVED');
__('problemstate_CLOSED');
__('problemstate_DELETED');

/** Vote states */
__('VOTE_Yes');
__('VOTE_No');
__('VOTE_Ignore');

/** /user/view */
__('USR_ACCSTATUS_0');
__('USR_ACCSTATUS_1');
?>