<?= $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Colaboration software application</title>
	<?php echo $this->headLink()->appendStylesheet('/styles/base.css') ?>
</head>
<body>
<div id="mainBox">
	<div id="mainHeader">
		<div id="mainNavigation">
			<a href="/index">Main</a>
			<a href="/problemarea/index">Nastavenie</a>
		</div>
	</div>
	<div class="mainSep1"></div>
	<div class="mainSep2"></div>
	
	<div>
		<div id="mainMenuLeft">
			<div class="menuBox">
				<span class="title">Problémová oblasť</span>	
				<a class="row" href="/problemarea/add">Pridať novú</a>
			</div>
			<?=$this->layout()->sidebar;?>
			
		</div>
		
		<div id="mainMenuRight">
			<div id="mainMenuRight2">
				<?=$this->layout()->content;?> 
			</div>
		</div>
	</div>
	<div id="mainFooter">
		<small id="mainFooter2">
			(c) 2007, František Ďurajka
		</small>
	</div>
</div>
</body>
</html>