<?php $this->placeholder('nav')->captureStart('APPEND'); ?>
	<div class="menuBox">
		<span class="title"><?=$this->translate('Problem Area'); ?></span>	
		<a class="row" href="/problemarea/index"><?=$this->translate('View problem areas');?></a>
	</div>
<?php $this->placeholder('nav')->captureEnd(); ?>

<h2><?=$this->translate('New Problem Area Title');?></h2>
<?php echo $this->form->render();?>