<h2>Zoznam všetkých problémov v problémovej oblasti</h2>
<script type="text/javascript">
	var Gridka;
	var statusCombo;
	var categoryCombo;
	var filterText;
	var DataStore;
	var listingCount = 25;
	var filterGrid = function () {
		DataStore.load({
			params: {
				start: 0,
				limit: listingCount
			}
		});
	}
	Ext.onReady(function() {
		var stavStore = new Ext.data.SimpleStore({
        	id: 'catIdxxx',
        	fields: ['id', 'state'],
      		data : [
      			['', 'Všetky stavy'],
      			['NEW', 'Novy'],
      			['APPROVED', 'Potvrdený'],
      			['SOLVED', 'Vyriešený'],
      			['CLOSED', 'Uzatvoreny']
      		]
    	});
		var categoryStore = new Ext.data.SimpleStore({
			id: 'catIdx',
        	fields: ['Id', 'Name'],
        	autoLoad: true,
        	url: '/category/ajax-combo'
    	});
    	statusCombo = new Ext.form.ComboBox({
			        id: 'idStatus',
			        store: stavStore,
			        displayField: 'state',
			        valueField: 'id',
			        forceSelection: false,
			        editable: true,
			        allowBlank: true,
			        mode: 'local',
			        triggerAction: 'all',
			        width: 110,
			        emptyText: 'Všetky stavy'
			    });
		categoryCombo = new Ext.form.ComboBox({
			    	store: categoryStore,
			    	displayField: 'Name',
			    	valueField: 'Id',
			    	forceSelection: false,
			    	editable: true,
			    	allowBlank: true,
			    	<?php if ($this->CategoryId): ?>
			    		value: <?=(int)$this->CategoryId?>,
			    	<?php endif; ?>
			    	triggerAction: 'all',
			    	emptyText: 'Všetky kategórie'
			    });
		filterText = new Ext.app.SearchField({
					id: 'idtrigger',
					width: 300,
					onTrigger2Click: filterGrid
				});
    	var Filter = new Ext.Toolbar({
			renderTo: 'gridkaFilterDiv',
			border: true,
			items: [
				'Hľadať: ', 
				statusCombo, '-',
			    categoryCombo, '-',
				filterText
			]
		});
	});	
</script>
<div id="gridkaFilterDiv" style="border: 1px solid #A9BFD3; border-bottom: 0; margin-bottom: 10px;"></div>

<script type="text/javascript">
Ext.onReady(function() {
	var ColumnModel;
	var expander = new Ext.grid.RowExpander({
        tpl : new Ext.Template(
            '<p style="padding: 5px;">{Definition}</p>'
        )
    });
	DataStore = new Ext.data.Store({
		id: 'DataStoreId',
		proxy: new Ext.data.HttpProxy({
				url: '/problemarea/ajax-problems',
				method: 'POST'				
			}),
		reader: new Ext.data.JsonReader({
					root: 'rows',
					totalProperty: 'total',
					id: 'Id'
				}, [
					{name: 'Id', type: 'int', mapping: 'Id'},
					{name: 'Name', type: 'string', mapping: 'Name'},
					{name: 'Username', type: 'string', mapping: 'Username'},
					{name: 'Created', type: 'string', mapping: 'Created'},
					{name: 'FullCategoryName', type: 'string', mapping: 'FullCategoryName'},
					{name: 'State', type: 'string', mapping: 'State'},
					{name: 'Definition', type: 'string', mapping: 'Definition'}
			]),
		listeners: {
			beforeload: function () {
				DataStore.baseParams = {
					status: statusCombo.getValue(),
					category: categoryCombo.getValue(),
					text: filterText.getValue()
				}
			}			
		},
		sortInfo: {field: 'Id', direction: "ASC"}
	});
	
	// Columns used
	renderName = function(data, cellmd, record, row, col, store) {
		return '<a href="/problem/view/Id/' + record.get('Id') + '">' + data + '</a>';
	}
	renderState = function(data, cellmd, record, row, col, store) {
		switch (data) {
			case 'NEW':
				return 'Nový';
			case 'APPROVED':
				return 'Potvrdený';
			case 'SOLVED':
				return 'Vyriešený';
			case 'DELETED':
				return 'Vymazaný';
		}
		return data;
	}
	ColumnModel = new Ext.grid.ColumnModel( [ 
		 expander, {
		 	header: 'Názov',
		 	dataIndex: 'Name',
		 	readOnly: true,
		 	width: 250,
		 	hidden: false,
		 	renderer: renderName
		 }, {
		 	header: 'Stav',
		 	dataIndex: 'State',
		 	readOnly: true,
		 	width: 75,
		 	hidden: false,
		 	renderer: renderState
		 },{
		 	header: 'Hlavná kategória',
		 	dataIndex: 'FullCategoryName',
		 	readOnly: true,
		 	width: 120,
		 	hidden: false
		 }, {
		 	header: 'Vytvoril',
		 	dataIndex: 'Username',
		 	readOnly: true,
		 	width: 80,
		 	hidden: false
		 }, {
		 	header: 'Vytvorený dňa',
		 	dataIndex: 'Created',
		 	readOnly: true,
		 	width: 150,
		 	hidden: false
		 }]
	);
	ColumnModel.defaultSortable = true;
	
	// Gridka
	Gridka = new Ext.grid.GridPanel({
		id: 'GridkaId',
		store: DataStore,
		cm: ColumnModel,
		autoHeight: true,
		selModel: new Ext.grid.RowSelectionModel({singleSelect:false}),
		renderTo: 'gridkaDiv',
		plugins: expander,
		viewConfig: {
            forceFit:true
        },
		tbar: [{
			text: 'Nový problém',
			tooltip: 'Pridať nový problém',
			iconCls: 'addButton',
			handler: function() {
				window.location='/problemarea/addproblem';
			}
		}, '-'],
		bbar: new Ext.PagingToolbar({
			pageSize: listingCount,
			store: DataStore,
			displayInfo: true,
			displayMsg: 'Zobrazujem problémy {0} - {1} z {2}', 
			emptyMsg: 'Žiadne problémy'
		})
	});	
	DataStore.load({
		params: {
			start: 0,
			limit: listingCount
		}
	});
});
</script>
<div id="gridkaDiv"></div>