<h2>Problémové oblasti</h2>
<p>
  Prosím vyberte si problémovú oblasť, pre ktorú chcete zobraziť stav jej 
  rozpracovania.
</p>

<?=$this->FlashMessages(); ?>

<?php if (count($this->areas) > 0): ?>
	<table class="std">
  	<thead>
    	<tr>
    		<th></th>
      		<th>Názov problémovej oblasti</th>
      		<th>Stav riešenia</th>
      		<th>Posledná zmena</th>      
    	</tr>
	</thead>
	<tbody>
<?php foreach ($this->areas as $key=>$pa): ?>
	
    <tr>
      <td>
      	<a href="/problemarea/view/id/<?=$pa['Id']?>" title="Zobraziť podrobnosti">Vybrať</a>
      </td>
      <td><?=$pa['Name']?></td>
      <td>todo</td>
      <td>todo</td>
      
    <tr>
<?php endforeach; ?>
	</tbody>
	</table>
<?php else: ?>
<p>
	<?=$this->translate('No problema area exists yet. Please add one.') ?>
</p>
<?php endif; ?>