<h2><?=$this->pa->Name;?></h2>
<?=$this->FlashMessages(); ?>
<p>
	<label>Created:</label><?=$this->pa->Created;?><br />
	<label>Posledná zmena:</label> 10.1.2008, (<a href="#">Peter Zakuskový</a>)
</p>
<p>
	<?=$this->pa->Definition; ?>
</p>

<h3>Zmeny v problémovej oblasti</h3>
... 


<p>
	<a class="btn" href="/problemarea/change/Id/<?=$this->pa->Id?>" title="Identitfy new problem">Zmeniť definíciu</a>
</p>