<div class="divBox">
	<?php if ($this->authenticated): ?>
		<b><?=$this->translate('role_'.$this->user->RoleId)?>:</b> <?=$this->user->getFullname();?>
		

		<div style="text-align: right">
			<a href="/auth/logout" title="logout">sign out</a>
		</div>
	<?php else: ?>
		<p style="padding: 5px 0 5px 0; margin: 0;">
		<?=__('Please log into the system');?>
		</p>
		<form action="/auth/login" class="menuBoxBody" method="post">
			<input type="hidden" name="redirect" value="<?=$this->redirect;?>" />
			<label style="color: grey">Prihlasovacie meno:</label><br /><input type="text" name="username" value="" /><br />
			<label style="color: grey">Heslo:</label><br /><input type="password" name="password" value="" />
			<br /><input type="submit" value="Prihlásiť sa" />
		</form>
	<?php endif; ?>
</div>