<h2>Postupnosť riešenia</h2>

<?php if ($this->WARNING_ZV): ?>
<p style="color: red;">
	<strong>Upozornenie</strong>: Niektoré riešenia majú závislosť na neuzatvorené problémy.
</p>
<?php endif; ?>


<table class="std">
  <tr>
  	<th>#</th>
    
    <th>Číslo</th>
    <th>Závislosť</th>
    <th>Názov problému</th>
    
    <th>Závažnosť</th>
  </tr>
  <?php $i=0; foreach ($this->problems as $p): $i++; ?>
  <tr>
  	<td nowrap><?=$i?>.</td>
    <td><?=$p['Id']?>. </td>
    <td><?=implode(', ', $p['Dependence']); ?></td>
    <td nowrap style="width: 100%">
    	<a href="/problem/view/Id/<?=$p['Id']?>">
    		<?=$p['Name']?>
    	</a>
    </td>
    <td style="width: 20px; text-align: center;"><?=number_format($p['Importance'], 2)?></td>
  </tr>
  <?php endforeach; ?>
</table>

<p>
	* Vygenerované poradie zodpovedá aktuálnej závažnosti problémov a ich závislostiam.
</p>

