<h2>Problém: <?=$this->problem->Name?></h2>
<div style="border: 1px solid grey">
<dl>
	<dt>Plný názov</dt>
	<dd><?=$this->problem->FullName;?></dd>
	
	<dt>Definition</dt>
	<dd><?=$this->problem->Definition;?></dd>
	
	<dt>Created</dt>
	<dd><?=$this->problem->Created?></dd>
	
	<dt>Modified</dt>
	<dd><?=$this->problem->Modified?></dd>
	
</dl>
</div>
<p>
	<a class="btn" href="/problem/changedefinition/Id/<?=$this->problem->Id?>">Change definition</a>
	<a class="btn" href="/problem/remove/Id/<?=$this->problem->Id?>">Remove</a>
	<a class="btn" href="/problem/remove/Id/<?=$this->problem->Id?>">Zobraziť históriu</a>
</p>

<h3>Riešenia</h3>
<table>
	<tr>
		<th></th>
		<th></th>
	</tr>
	
</table>

<h3>Diskusia</h3>
<p>
	...
</p>

<h4>Pridať prispevok do diskusie</h4>


