<h2>Registrácia nového používateľa</h2>
<?php
$this->form->getElement('Podmienky')->setValue('Registrácia do systému je bezplatná. Jedinou podmienkou je akceptovanie nasledovných pravidiel pre prácu so systémom. Ich akceptáciu potvrdťe zaškrtnutím tlačidla "Súhlasím s podmienkami registrácie". 

Akceptáciou tohto formulára sa používateľ zaväzuje, že nebude do systému prispievať akýmikoľvek príspevkami, ktoré majú obscénny, vulgárny, sexuálno-orientovaný alebo akýkoľvek nelegálny alebo nemorálny charakter. Taktiež žiadame používateľov, aby sa svojími príspevkami vyjadrovali výlučne iba riešeným problémovým témam. 

Správcovia tohto systému si rezerbujú právo na vymazanie alebo zmenu príspevkov v akomkoľvek prípade.');
?>
<?=$this->form?>
<p>
	<small>
		1) Položky uvedené tlstým písmom je nutné uvádzať.
	</small>
</p>
<p>
	<small>
		2) Pre dokončnie registrácie je potrebné overenie Vašej e-mailovej adresy za pomoci 
		kontrolného e-mailu. 
	</small>
</p>