<?php $this->placeholder('nav')->captureStart('APPEND'); ?>
	<div class="menuBox">
		<span class="title"><?=$this->translate('Problem areas'); ?></span>
		<a class="row" href="/problemarea/add"><?=$this->translate('Add new problem area');?></a>	
	</div>
<?php $this->placeholder('nav')->captureEnd('APPEND'); ?>

<h2>Zoznam problémových oblastí</h2>

<?=$this->FlashMessages(); ?>

<?php if (count($this->areas) > 0): ?>
<?php foreach ($this->areas as $key=>$pa): ?>
<table class="ProblemAreaTable">
	<tr>
		<th>
			<a href="/problemarea/view/id/<?=$pa['Id']?>"><?=$pa['Name']?></a>
		</th>
	</tr>
	<tr>
		<td colspan="2"><?=$pa['Description']?></td>
	</tr>
</table>
<?php endforeach; ?>
<?php else: ?>
<p>
	<?=$this->translate('No problema area exists yet. Please add one.') ?>
</p>
<?php endif; ?>
