<h2>Zoznam problémových oblastí</h2>

<?=$this->FlashMessages(); ?>

<?php if (count($this->areas) > 0): ?>
<?php foreach ($this->areas as $key=>$pa): ?>
<table class="ProblemAreaTable">
	<tr>
		<th><?=$pa['Name']?></th>
	</tr>
	<tr>
		<td colspan="2"><?=$pa['Description']?></td>
	</tr>
</table>
<?php endforeach; ?>
<?php else: ?>
<p>
	<?=$this->translate('No problema area exists yet. Please add one.') ?>
</p>
<?php endif; ?>
