<h2>Čo tu najdeš?</h2>
<p>
	Vítam Vás v kolaboračnom informačnom systéme. Tento systém vznikol ako projekt diplomovej práce. Jeho úlohou je 
	napomáhať pri riešení problémov v rôznych problémových oblasťiach. Mojou zvolenou oblasťou sú problémy tíkajúce 
	sa kvality ubytovania na <strong>internáte Mladosť</strong>. 
</p>
<br />

<h3>Trápi ťa problém! - daj o ňom vedieť!</h3>
<p>
	Úlohou totho projektu je práve napomôcť pri riešení problémov, ktoré trápia ubytovaných študentov. 
</p>
<p>
	Problémov môže byť veľa a nie o všetkých vedenie internátov vie. Preto je dôležité dať o svojom probléme vedieť, teda podeliť
	sa s ním ostatnými, diskutovať o ňom a nájsť spoločné riešenie. Toto riešenie poslúži ako podklad, ktorý napomôže k ich skorému 
	odstráneniu. 
</p>
<p>
	<a class="btn" href="/problemarea/addproblem">&raquo; Štart: Nový problém</a>
</p>
<br />

<h3>Máš svoj názor na riešenie? - podeľ sa!</h3>
<p>
	Máš odlišný názor alebo nápad ako riešiť niektorý problém? Podeľ sa s ním s ostatnými prostredníctvom 
	nových návrhov alebo komentárov. Taktiež môžeš vyjadriť svoj názor na jednotlivé riešenia, ktoré je správne alebo 
	ktoré je nesprávne.
</p>
<p>
	<a class="btn" href="#">&raquo; Štart: Zoznam problémov</a>
</p>

<br />
<p>
	Apríl, 2008
</p>