<div class="divBox">
	<span style="float: right"><?=$this->countAll?></span>Počet problémov: <br />
	<span style="float: right"><?=$this->countNew?></span>Nových: <br />
	<span style="float: right"><?=$this->countApproved?></span>Schválených: <br />
	<span style="float: right"><?=$this->countSolved?></span>Vyriešených: <br />
	<span style="float: right"><?=$this->countClosed?></span>Uzavretých: <br />
</div>



			