<h2>Problémové oblasti</h2>
<p>
  Prosím vyberte si problémovú oblasť, s ktorou chcete pracovať.
</p>

<?=$this->FlashMessages(); ?>

<?php if (count($this->areas) > 0): ?>
	<table class="std">
  	<thead>
    	<tr>
    		<th>Názov problémovej oblasti</th>
      		<th></th>      
    	</tr>
	</thead>
	<tbody>
<?php foreach ($this->areas as $key=>$pa): ?>
	
    <tr>
      <td><?=$pa['Name']?></td>
      <td style="text-align: center;">
      	<input type="button" value="Vybrať ako predvolenú" onclick="window.location = '/problemarea/view/id/<?=$pa['Id']?>';" />
      </td>
      
    <tr>
<?php endforeach; ?>
	</tbody>
	</table>
<?php else: ?>
<p>
	<?=$this->translate('No problema area exists yet. Please add one.') ?>
</p>
<?php endif; ?>