<?php $this->placeholder('nav')->captureStart('APPEND'); ?>
	<a class="row" href="/problemarea/change"><?=$this->translate('Change proporties');?></a>
	<a class="row" href="/problemarea/addproblem"><?=$this->translate('Add new problem');?></a>
<?php $this->placeholder('nav')->captureEnd(); ?>

<h1><?=$this->pa['Name'];?></h1>

<p>
	<label>Created:</label><?=$this->pa['Created'];?><br />
	<label>Posledná zmena:</label> 10.1.2008, (<a href="#">Peter Zakuskový</a>)
</p>
<p>
	<?=$this->pa['Description']; ?>
</p>

<h3>Zoznam problémov v problémovej oblasti</h3>
<table class="std">
	<thead>
    <tr>
		<th>Názov problém</th>
		<th>Posledná zmena</th>   
		<th>Stav riešenia</th>   
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Suchý vzduch na izbe</td>
		<td>10.1.2008</td>
		<td>Vyriešený</td>
	</tr>
	</tbody>
</table>