<h2><?=$this->pa->Name;?></h2>
<?=$this->FlashMessages(); ?>
<p>
	<label>Created:</label><?=$this->pa->Created;?><br />
	<label>Posledná zmena:</label> 10.1.2008, (<a href="#">Peter Zakuskový</a>)
</p>
<p>
	<?=$this->pa->Definition; ?>
</p>

<h3>História zmien problémovej oblasti</h3>
<table>
<tr>
	<th>Zmena</th>
	<th>Dátum</th>
	<th>Autor</th>
	<th>Zobraziť</th>
</tr>
<?php $i=count($this->changes)+1; foreach ($this->changes as $change): $i-- ?>
<tr>
	<td><?=$i;?></td>
	<td><?=$change->Created?></td>
	<td></td>
	<td><?=$change->Name?></td>
</tr>
<?php endforeach; ?>
</table> 


<p>
	<a class="btn" href="/problemarea/change/Id/<?=$this->pa->Id?>" title="Identitfy new problem">Zmeniť definíciu</a>
</p>