<h2>Informácie o používateľovi</h2>
<?=$this->FlashMessages(); ?>
<fieldset class="std">
	<legend>Základné informácie</legend>
	<dl class="std">
		<dt>Prihlasovacie meno:</dt>
		<dd><strong><?=$this->usr->Username?></strong></dd>
		
		<dt>Stav účtu:</dt>
		<dd><?=__('USR_ACCSTATUS_'.$this->usr->Active)?></dd>
		
		<dt>Používateľské meno:</dt>
		<dd><?=$this->usr->FullName?></dd>
		
		
		<dt>E-mail:</dt>
		<dd><a href="mailto:<?=$this->usr->EMail;?>"><?=$this->usr->EMail;?></a></dd>

		<dt>Posledne prihlásený:</dt>
		<dd><?=$this->usr->LastLogged?></dd>
		
		<dt>Typ účtu:</dt>
		<dd><?=__('role_'.$this->usr->RoleId)?></dd>
	</dl>
</fieldset>
<fieldset class="std">
	<legend>Aktivity používateľa</legend>
	<dl class="std">
		<dt>Pridaných problémov:</dt>
		<dd>0</dd>
		
		<dt>Pridaných riešení:</dt>
		<dd>0</dd>
		
		<dt>Pridaných Komentárov:</dt>
		<dd>0</dd>
		
		<dt>Počet hlasovaní:</dt>
		<dd>0</dd>
	</dl>	
</fieldset>

<p>
	<?php if ($this->user->Id != $this->usr->Id): ?>
		<a class="btn" href="/user/change-role/id/<?=$this->usr->Id?>">Zmeniť typ účtu</a>
	
		
		<?php if ($this->usr->Active): ?>
			<a class="btn" onclick="return confirm('Naozaj si prajete deaktivovať používateľský účet?');" href="/user/deactivate/id/<?=$this->usr->Id?>">Deaktivovať</a>
		<?php else: ?>
			<a class="btn" href="/user/activate/id/<?=$this->usr->Id?>">Aktivovať</a>
		<?php endif; ?>
	<?php endif;?>
</p>

