<h2>
	<span style="float: right">
		<?=$this->translate('problemstate_'.$this->problem->State)?>
	</span>
	<?=$this->problem->Name?>
</h2>
<?=$this->FlashMessages(); ?>
<fieldset id="problemView">
	<legend>Definícia problému:</legend>
	<?=$this->problem->Definition;?>

<script type="text/javascript">
function voteAccept(vote) {
	
	// set voting text
	$('hlasujem').innerHTML = 'Hlasujem ...';
	
	// ajax request
	new Ajax.Request('/problem/vote-accept-'+vote+'/problemId/<?=$this->problem->Id?>', {
		method: 'post',
		onSuccess: function(transport) {
			var json = transport.responseText.evalJSON();
			
			var out = 'Hlasovali ste: ';
			switch (json.Vote) {
				case '<?=ProblemAccept::VOTE_YES?>':
					out += '<b><?=__('VOTE_'.ProblemAccept::VOTE_YES)?></b>';
					break;
				case '<?=ProblemAccept::VOTE_NO?>':
					out += '<b><?=__('VOTE_'.ProblemAccept::VOTE_NO)?></b>';
					break;
				case '<?=ProblemAccept::VOTE_IGNORE?>':
					out += '<b><?=__('VOTE_'.ProblemAccept::VOTE_IGNORE)?></b>';
					break;
			}
			out += '<span id="voteChangeHide">';
			out += ' , <a href="#" onclick="$(\'voteChangeHide\').hide(); $(\'voteChange\').show(); return false;">Zmeniť</a>';
			out += '</span>';
			out += '<span id="voteChange" style="display: none"> / ';
			switch (json.Vote) {
				case '<?=ProblemAccept::VOTE_YES?>':
					out += '<a onclick="return voteAccept(\'no\');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_NO)?></b></a> /';
					out += '<a onclick="return voteAccept(\'ignore\');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_IGNORE)?></b></a>';
					break;
				case '<?=ProblemAccept::VOTE_NO?>':
					out += '<a onclick="return voteAccept(\'yes\');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_YES)?></b></a> /';
					out += '<a onclick="return voteAccept(\'ignore\');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_IGNORE)?></b></a>';
					break;
				case '<?=ProblemAccept::VOTE_IGNORE?>':
					out += '<a onclick="return voteAccept(\'yes\');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_YES)?></b></a> /';
					out += '<a onclick="return voteAccept(\'no\');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_NO)?></b></a>';
					break;
			}
			out += '</span>';
			$('hlasujem').innerHTML = out;
			
			// update voted informations
			new Ajax.Request('/problem/ajax-vote-info/problemId/<?=$this->problem->Id?>', {
				method: 'post',
				onSuccess: function (transport) {
					var json = transport.responseText.evalJSON();
					$('voteYes').innerHTML 		= json.votes.Yes;
					$('voteNo').innerHTML 		= json.votes.No;
					$('voteIgnore').innerHTML 	= json.votes.Ignore;
					$('voteVoted').innerHTML 	= json.voted;
					$('voteTotal').innerHTML 	= json.total;
				}
			}); 	
		}
	});
	return false;
}
</script>

<p style="margin-top: 15px; margin-bottom: 0; border-top: 1px solid silver; padding-top: 10px;">
	
	<?php if ($this->isAllowed('PROBLEM', 'ACCEPT_VOTE')): ?>
	<?php if ($this->problem->State == Problem::STATE_NEW): ?>
	<span style="float: right; text-align: right;">
		<span id="hlasujem">
		<?php if ($this->acceptVote->voted()):?>
			Hlasovali ste: <b><?=__('VOTE_'.$this->acceptVote->Vote)?></b>
			<span id="voteChangeHide">, <a href="#" onclick="$('voteChangeHide').hide(); $('voteChange').show(); return false;">Zmeniť</a></span><span id="voteChange" style="display: none">
				/ 
				<?php if ($this->acceptVote->Vote == ProblemAccept::VOTE_YES): ?>
					<a onclick="return voteAccept('no');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_NO)?></b></a> /
					<a onclick="return voteAccept('ignore');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_IGNORE)?></b></a>
						
				<?php endif; ?>
				<?php if ($this->acceptVote->Vote == ProblemAccept::VOTE_NO): ?>
					<a onclick="return voteAccept('yes');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_YES)?></b></a> /
					<a onclick="return voteAccept('ignore');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_IGNORE)?></b></a>
					
				<?php endif; ?>
				<?php if ($this->acceptVote->Vote == ProblemAccept::VOTE_IGNORE): ?>
					<a onclick="return voteAccept('yes');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_YES)?></b></a> /
					<a onclick="return voteAccept('no');" href="#"><b><?=__('VOTE_'.ProblemAccept::VOTE_NO)?></b></a>
				<?php endif; ?>
			</span>
		<?php else: ?>
			Akceptovať: 
			<a onclick="return voteAccept('yes');" href="#"><b>Ano</b></a> /
			<a onclick="return voteAccept('no');" href="#"><b>Nie</b></a> /
			<a onclick="return voteAccept('ignore');" href="#"><b>Neviem</b></a>
		<?php endif; ?>
		</span>
	</span>
	<?php endif; ?>
	<?php endif; ?>
	
	
	<!-- Autor moze pozmenit definiciu ak nie je new -->
	<?php if ($this->problem->State == Problem::STATE_NEW && $this->problem->CreatedBy == $this->user->Id): ?>
		<a href="/problem/changedefinition/Id/<?=$this->problem->Id?>"><b>Upraviť definíciu</b></a>
	<?php endif; ?>
</p>
</fieldset>


<?php if ($this->problem->State == Problem::STATE_NEW && ($this->isAllowed('PROBLEM', 'VIEW_ACCEPT_STATS') or $this->isAllowed('PROBLEM', 'ACCEPT'))): ?>
<br />
<fieldset>
	<legend>Priebežná štatistika hlasovania:</legend>
	<span id="acceptStats">
		Akceptovalo <strong id="voteYes"><?=$this->voteInfo->getVote(ProblemAccept::VOTE_YES);?></strong>, Neakceptovalo <strong id="voteNo"><?=$this->voteInfo->getVote(ProblemAccept::VOTE_NO);?></strong>, Nevedelo <strong id="voteIgnore"><?=$this->voteInfo->getVote(ProblemAccept::VOTE_IGNORE);?></strong> osoby. Celkovo hlasovalo <strong id="voteVoted"><?=$this->voteInfo->getVoted();?></strong> z <strong id="voteTotal"><?=$this->voteInfo->getTotal();?></strong> možných účastníkov.
	</span>
	<p style="margin-top: 15px; margin-bottom: 0; border-top: 1px solid silver; padding-top: 10px;">
		<span id="ackLinky">
			<a onclick="$('akcForm').show(); $('ackLinky').hide(); return false;" href="#"><strong>Akceptovať problém</strong></a> 
			/ 
			<a onclick="$('decForm').show(); $('ackLinky').hide(); return false;" href="#"><strong>Zavrhnúť problém</strong></a>
		</span>
	</p>
	<form class="std" id="akcForm" method="post" action="/problem/accept/problemId/<?=$this->problem->Id?>" style="display: none">
		<fieldset>
			<legend>
				<input name="accept-comment" type="checkbox" onclick="if (this.checked) {$('accBody').show();} else {$('accBody').hide();}" value="1" checked />  
				<strong>Pridaj informatívny komentár k problému</strong>
			</legend>
			<dl id="accBody">
				<dt>Hlavička:</dt>
				<dd><input type="text" size="60" value="Systémová správa" name="accept-comment-title" /></dd>
				<dt>Komentár:</dt>
				<dd>
					<textarea name="accept-comment-body" class="mceEditor" style="width: 100%">
						<p>Problém bol akceptovaný.</p>
						<p>Výsledky hlasovania: Akceptovalo(<?=$this->voteInfo->getVote(ProblemAccept::VOTE_YES)?>), Neakceptovalo(<?=$this->voteInfo->getVote(ProblemAccept::VOTE_NO)?>), Zdržalo sa(<?=$this->voteInfo->getVote(ProblemAccept::VOTE_IGNORE)?>), celkový počet <?=$this->voteInfo->getVoted()?> hlasov.</p>
					</textarea>
				</dd>
			</dl>
		</fieldset>
		<dl>
			<dt>Poznámka k zmene:</dt>
			<dd><textarea name="accept-note" cols="60" rows="1"></textarea></dd>
		</dl>
		<p>
			<input type="submit" value="Akceptovať" />
			<input type="button" onclick="$('akcForm').hide(); $('ackLinky').show(); return false;" value="Zrušiť" />
		</p>
	</form>
	<form class="std" id="decForm" method="post" action="/problem/decline/problemId/<?=$this->problem->Id?>" style="display: none">
		<fieldset>
			<legend>
				<input name="decline-comment" type="checkbox" onclick="if (this.checked) {$('decBody').show();} else {$('decBody').hide();}" value="1" checked />  
				<strong>Pridaj informatívny komentár k problému</strong>
			</legend>
			<dl id="decBody">
				<dt>Hlavička:</dt>
				<dd><input type="text" size="60" value="Systémová správa" name="decline-comment-title" /></dd>
				<dt>Komentár:</dt>
				<dd>
					<textarea name="decline-comment-body" class="mceEditor" style="width: 100%">
						<p>Problém nebol akceptovaný.</p>
						<p>Výsledky hlasovania: Akceptovalo(<?=$this->voteInfo->getVote(ProblemAccept::VOTE_YES)?>), Neakceptovalo(<?=$this->voteInfo->getVote(ProblemAccept::VOTE_NO)?>), Zdržalo sa(<?=$this->voteInfo->getVote(ProblemAccept::VOTE_IGNORE)?>), celkový počet <?=$this->voteInfo->getVoted()?> hlasov.</p>
					</textarea>
				</dd>
			</dl>
		</fieldset>
		<dl>
			<dt>Poznámka k zmene:</dt>
			<dd><textarea name="decline-note" cols="60" rows="1"></textarea></dd>
		</dl>
		<p>
			<input type="submit" value="Zavrhnúť problém" />
			<input type="button" onclick="$('decForm').hide(); $('ackLinky').show(); return false;" value="Zrušiť" />
		</p>
	</form>
</fieldset>
<?php endif; ?>

<h3>Komentáre k zadanému problému:</h3>
<p id="commentNone">	
	Žiadne.
</p>
<input type="button" value="Pridať komentár" />

<!--  zobrazi jednotlive komentare k problemom
<h3>Diskusia (<?=count($this->comments)?> príspevky/ov)</h3>
<?php foreach ($this->comments as $comment): ?>
	<?=$this->partial('problem/partial-comment.phtml', array('comment' => $comment)); ?>
<?php endforeach; ?>
<p>
	<a class="btn" href="/problem/add-comment/Id/<?=$this->problem->Id?>">Pridať komentár</a>
</p>
-->

