<script type="text/javascript">
function accVote(problemId, vote) {
	$('accInfo_'+problemId).innerHTML = 'Hlasujem ...';
	new Ajax.Request('/problem/vote-accept-'+vote+'/problemId/'+problemId, {
		method: 'post',
		onSuccess: function (transport) {
			new Ajax.Updater('accInfo_' + problemId, '/problem/display-status/problemId/'+problemId);
			new Ajax.Updater('acceptStats', '/problem/display-accept-status/problemId/'+problemId);
		}
	});
	return false;
}
function importanceVote(problemId, vote) {
	$('importanceInfo_'+problemId).innerHTML = 'Hlasujem ...';
	new Ajax.Request('/problem/vote-importance/problemId/'+problemId+'/vote/'+vote, {
		method: 'post',
		onFailure: function (transport) {
			$('accInfo_'+problemId).innerHTML = 'Failed ...';
		},
		onSuccess: function (transport) {
			new Ajax.Updater('importanceInfo_'+problemId, '/problem/display-importance-status/problemId/'+problemId);
		}
	});
	return false;
}
</script>
<script type="text/javascript">
function svVote(solutionId, vote) {
	$('svInfo_'+solutionId).innerHTML = 'Hlasujem ...';
	new Ajax.Request('/solution/vote-accept-'+vote+'/solutionId/'+solutionId, {
		method: 'post',
		onSuccess: function (transport) {
			new Ajax.Updater('svInfo_'+solutionId, '/solution/display-status/solutionId/'+solutionId);
		}
	});}
</script>

<h2><span style="float: right"><?=$this->translate('problemstate_'.$this->problem->State)?></span><?=$this->problem->Name?></h2>
<?=$this->FlashMessages(); ?>

<fieldset id="problemView">
	<legend>Definícia problému:</legend>
	<div>
		<?=$this->problem->Definition;?>
	</div>
	<p style="margin-top: 15px; margin-bottom: 0; border-top: 1px solid silver; padding-top: 10px;">
		<?php if ($this->isAllowed('PROBLEM', 'ACCEPT_VOTE')): ?>
			<?php if ($this->authenticated): ?>
			<?php if ($this->problem->State == Problem::STATE_NEW): ?>
				<span style="float: right;">
					<?=$this->action('display-status', 'problem', null, array('problemId' => $this->problem->Id, 'enableLayout'=>1))?>		
				</span>
			<?php endif; ?>
			<?php endif; ?>
		<?php endif; ?>
	
		<?php if ($this->isAllowed('PROBLEM', 'IMPORTANCE_VOTE')): ?>
		<?php if ($this->problem->State == Problem::STATE_APPROVED): ?>
			<?php if ($this->authenticated): ?>
			<span style="float: right;">
				<?=$this->action('display-importance-status', 'problem', null, array('problemId' => $this->problem->Id, 'enableLayout'=>1))?>				
			</span>
			<?php endif; ?>
		<?php endif; ?>
		<?php endif; ?>
		
		<?php if ($this->problem->State == Problem::STATE_NEW && $this->problem->CreatedBy == $this->user->Id): ?>
			<a href="/problem/changedefinition/Id/<?=$this->problem->Id?>"><b>Upraviť definíciu</b></a> - 
			- <a href="/problem/history/problemId/<?=$this->problem->Id;?>"><b>História</b></a>
		<?php else: ?>
			<a href="/problem/history/problemId/<?=$this->problem->Id;?>"><b>História</b></a>
		<?php endif; ?>		
		<?php if ($this->isAllowed('PROBLEM', 'SOLVE')): ?>
		<?php if ($this->problem->State == Problem::STATE_APPROVED): ?>
			- <a onclick="return confirm('Naozaj chcete ukončiť riešenie problému?');" href="/problem/solve/problemId/<?=$this->problem->Id;?>"><b>Ukonči riešenie</b></a>
		<?php endif; ?>
		<?php endif; ?> 		
	</p>
</fieldset>

<?php if ($this->problem->State == Problem::STATE_APPROVED or $this->problem->State == Problem::STATE_SOLVED or $this->problem->State == Problem::STATE_DELETED): ?>
<br />
<fieldset>
	<legend>Riešenia problému</legend>
	<p>
		<?php $i=0; foreach ($this->solutions as $solution): $i++;?>
		<div class="solutionDv1">
			<?=$i?>. <a href="/solution/view/id/<?=$solution->Id?>" class="solutionA1"><?=$solution->Name;?>.</a><br />
			<p class="solutionP">
				<?=$solution->Definition?>
				<span class="solutionBS">
					<?php if ($this->authenticated): ?>
					<span style="float: right;">
						<?php if ($solution->State == Solution::STATE_NEW): ?>
						<?php if ($this->problem->State == Problem::STATE_APPROVED): ?>
							<?=$this->action('display-status', 'solution', null, array('solutionId' => $solution->Id, 'enableLayout'=>1))?>
						<?php endif; ?>
						<?php endif; ?>
						<?php if ($solution->State == Solution::STATE_APPROVED): ?>
							Riešenie bolo <strong>akceptované</strong>.
						<?php endif; ?>
						<?php if ($solution->State == Solution::STATE_DELETED): ?>
							Riešenie je <strong>zavrhnuté</strong>.
						<?php endif; ?>
					</span>
					<?php endif; ?>
					<a href="/solution/view/id/<?=$solution->Id?>">Zobraziť podrobnosti</a>
				</span>
			</p>
		</div>
		<?php endforeach; ?>
		<?php if ($this->problem->State == Problem::STATE_APPROVED): ?>
		<p style="margin-bottom: 0; padding-bottom: 0;">
			<a href="/solution/create/id/<?=$this->problem->Id;?>">&raquo; <strong>Pridať riešenie</strong></a>
		</p>
		<?php else: ?>
		<p style="margin-bottom: 0; padding-bottom: 0;">
			* Problém je vyriešený, nie je možné pridávať nové riešenia.
		</p>
		<?php endif; ?>
	</p>
</fieldset>
<?php endif; ?>


<?php if ($this->problem->State == Problem::STATE_NEW): ?>
	<?php if ($this->isAllowed('PROBLEM', 'VIEW_ACCEPT_STATS') or $this->isAllowed('PROBLEM', 'ACCEPT')): ?>
	<br />
	<fieldset>
		<legend>Priebežná štatistika hlasovania:</legend>
		<span id="acceptStats">
			<?=$this->action('display-accept-status', 'problem', null, array('problemId' => $this->problem->Id, 'enableLayout'=>1))?>
		</span>
		<p style="margin-top: 15px; margin-bottom: 0; border-top: 1px solid silver; padding-top: 10px;">
			<span id="ackLinky">
				<a onclick="$('akcForm').show(); $('ackLinky').hide(); return false;" href="#"><strong>Akceptovať problém</strong></a> 
				/ 
				<a onclick="$('decForm').show(); $('ackLinky').hide(); return false;" href="#"><strong>Zavrhnúť problém</strong></a>
			</span>
		</p>
		
		<form class="std" id="akcForm" method="post" action="/problem/accept/problemId/<?=$this->problem->Id?>" style="display: none">
			<fieldset>
				<legend>
					<input name="accept-comment" type="checkbox" onclick="if (this.checked) {$('accBody').show();} else {$('accBody').hide();}" value="1" checked />  
					<strong>Pridaj informatívny komentár k problému</strong>
				</legend>
				<dl id="accBody">
					<dt>Hlavička:</dt>
					<dd><input type="text" size="60" value="Systémová správa" name="accept-comment-title" /></dd>
					<dt>Komentár:</dt>
					<dd>
						<textarea name="accept-comment-body" class="mceEditor" style="width: 100%">
							<p>Problém bol akceptovaný.</p>
							<p>Výsledky: <?=$this->action('display-accept-status', 'problem', null, array('problemId' => $this->problem->Id, 'enableLayout'=>1))?></p>
						</textarea>
					</dd>
				</dl>
			</fieldset>
			<dl>
				<dt>Poznámka k zmene:</dt>
				<dd><textarea name="accept-note" cols="60" rows="1"></textarea></dd>
			</dl>
			<p>
				<input type="submit" value="Akceptovať" />
				<input type="button" onclick="$('akcForm').hide(); $('ackLinky').show(); return false;" value="Zrušiť" />
			</p>
		</form>
		
		<form class="std" id="decForm" method="post" action="/problem/decline/problemId/<?=$this->problem->Id?>" style="display: none">
			<fieldset>
				<legend>
					<input name="decline-comment" type="checkbox" onclick="if (this.checked) {$('decBody').show();} else {$('decBody').hide();}" value="1" checked />  
					<strong>Pridaj informatívny komentár k problému</strong>
				</legend>
				<dl id="decBody">
					<dt>Hlavička:</dt>
					<dd><input type="text" size="60" value="Systémová správa" name="decline-comment-title" /></dd>
					<dt>Komentár:</dt>
					<dd>
						<textarea name="decline-comment-body" class="mceEditor" style="width: 100%">
							<p>Problém nebol akceptovaný.</p>
							<p>Výsledky: <?=$this->action('display-accept-status', 'problem', null, array('problemId' => $this->problem->Id, 'enableLayout'=>1))?></p>
						</textarea>
					</dd>
				</dl>
			</fieldset>
			<dl>
				<dt>Poznámka k zmene:</dt>
				<dd><textarea name="decline-note" cols="60" rows="1"></textarea></dd>
			</dl>
			<p>
				<input type="submit" value="Zavrhnúť problém" />
				<input type="button" onclick="$('decForm').hide(); $('ackLinky').show(); return false;" value="Zrušiť" />
			</p>
		</form>
		
	</fieldset>
	<?php endif; ?>
<?php endif; ?>

<br />

<h3>Diskusia k problému:</h3>
<?php if (count($this->comments) > 0): ?>
	<?php Zend_Registry::set('CommentNumber', 1); ?>
	<?php foreach ($this->comments as $comment): ?>
		<?=$this->partial('comment/partial-view.phtml', array('comment' => $comment));?>
	<?php endforeach; ?>
<?php else: ?>
	<fieldset style="margin-top: 10px; padding: 10px;">
		Žiadne komentáre.
	</fieldset>
<?php endif; ?>

<?=$this->partial('comment/partial-add.phtml', array(
	'problem' 	=> $this->problem,
	'filter'	=> $this->filter
));
?>