<h2>
	<span style="float: right">
		<?=$this->problem->State?>
	</span>
	Problém: <?=$this->problem->Name?>
</h2>
<?=$this->FlashMessages(); ?>
<p>
	Tu bude graficky prvok, ktory bude zobrazovat stav riesenia problemu. 
</p>


<div style="border: 1px solid grey">
<dl>
	<dt>Plný názov</dt>
	<dd><?=$this->problem->FullName;?></dd>
	
	<dt>Definition</dt>
	<dd><?=$this->problem->Definition;?></dd>
	
	<dt>Created</dt>
	<dd><?=$this->problem->Created?></dd>
	
	<dt>Modified</dt>
	<dd><?=$this->problem->Modified?></dd>
	
</dl>
</div>
<p>
	<span style="float: right">
		<a class="btn" href="/problem/decline">Zamietnúť</a>
		<a class="btn" href="/problem/accept">Akceptovať</a>
	</span>
	<a class="btn" href="/problem/changedefinition/Id/<?=$this->problem->Id?>">Change definition</a>
	<a class="btn" href="/problem/remove/Id/<?=$this->problem->Id?>">Zobraziť históriu</a>
</p>

<h3>Diskusia</h3>
<div style="border: 1px solid silver;">
	...
</div>
<p>
	<a class="btn" href="/problem/add-comment/Id/<?=$this->problem->Id?>">Pridať komentár</a>
</p>


